version: "2"
services:
  sfz-calculo-automatico-batch:
    image: repositorio-docker.sefaz.al.gov.br/sefaz/sfz-calculo-automatico:3.2.13-SNAPSHOT
    environment:
      SEFAZ_STACK_NOME: calculo-automatico-batch
      SEFAZ_STACK_VERSAO: 23
      SEFAZ_STACK_AMBIENTE: ${AMBIENTE}
      ROLE_ID: ${ROLE_ID}
      SECRET_ID: ${SECRET_ID}
      NOME_PROJETO: sfz-calculo-automatico-batch
      CMD_EXEC: api
      TZ: America/Maceio
      JWT_SECRET: ${CHAVE_SECRETA_JWT}
    labels:
      traefik.frontend.rule: Host:calculoautomaticoapi.sefaz.al.gov.br,calculoautomaticoapi.hom.sefaz.al.gov.br,calculoautomaticoapi.desenv.sefaz.al.gov.br
      traefik.port: "8000"
      traefik.enable: "true"
      traefik.backend: sfz-calculo-automatico
      io.rancher.container.pull_image: always
    tty: true
    volumes:
      - certificados:/certificados
    stdin_open: true
    networks:
      - calculo_network
  sfz-calculo-automatico-classificador-server:
    image: repositorio-docker.sefaz.al.gov.br/sefaz/sfz-calculo-automatico:3.2.13-SNAPSHOT
    environment:
      SEFAZ_STACK_NOME: calculo-automatico-batch
      SEFAZ_STACK_VERSAO: 23
      SEFAZ_STACK_AMBIENTE: ${AMBIENTE}
      ROLE_ID: ${ROLE_ID}
      SECRET_ID: ${SECRET_ID}
      NOME_PROJETO: sfz-calculo-automatico-classificador-server
      TZ: America/Maceio
      CMD_EXEC: cls_server
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.start_once: true
    tty: true
    volumes:
      - certificados:/certificados
    stdin_open: true
    networks:
      - calculo_network
  sfz-calculo-automatico-classificador-worker:
    image: repositorio-docker.sefaz.al.gov.br/sefaz/sfz-calculo-automatico:3.2.13-SNAPSHOT
    environment:
      SEFAZ_STACK_NOME: calculo-automatico-batch
      SEFAZ_STACK_VERSAO: 23
      SEFAZ_STACK_AMBIENTE: ${AMBIENTE}
      ROLE_ID: ${ROLE_ID}
      SECRET_ID: ${SECRET_ID}
      NOME_PROJETO: sfz-calculo-automatico-classificador-worker
      TZ: America/Maceio
      CMD_EXEC: cls_worker
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.start_once: true
    tty: true
    volumes:
      - certificados:/certificados
    stdin_open: true
    depends_on:
      - sfz-calculo-automatico-classificador-server
    networks:
      - calculo_network
  sfz-calculo-automatico-importador:
    image: repositorio-docker.sefaz.al.gov.br/sefaz/sfz-calculo-automatico:3.2.13-SNAPSHOT
    environment:
      SEFAZ_STACK_NOME: calculo-automatico-batch
      SEFAZ_STACK_VERSAO: 23
      SEFAZ_STACK_AMBIENTE: ${AMBIENTE}
      ROLE_ID: ${ROLE_ID}
      SECRET_ID: ${SECRET_ID}
      NOME_PROJETO: sfz-calculo-automatico-importador
      TZ: America/Maceio
      CMD_EXEC: imp
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.start_once: true
    tty: true
    volumes:
      - certificados:/certificados
    stdin_open: true
    networks:
      - calculo_network
networks:
  calculo_network: null
